import type { HorizontalBarSettings, Preset } from "@/types/editor";

const base: HorizontalBarSettings = {
  position: "bottom",
  widthPercent: 90,
  thickness: 8,
  marginX: 40,
  marginY: 60,
  radius: 4,
  fillColor: "#ffffff",
  trackColor: "#ffffff",
  fillOpacity: 1,
  trackOpacity: 0.25,
  glowEnabled: false,
  glowColor: "#5eead4",
  shadowEnabled: false,
  gradientEnabled: false,
  gradientFrom: "#5eead4",
  gradientTo: "#3b82f6",
  direction: "left-to-right",
  animation: "linear",
};

export const PRESETS: Preset[] = [
  {
    id: "minimal-creator",
    name: "Minimal Creator",
    description: "Thin white bar. Clean reels and shorts.",
    bar: {
      ...base,
      thickness: 4,
      radius: 2,
      widthPercent: 92,
      trackOpacity: 0.2,
    },
  },
  {
    id: "youtube-shorts",
    name: "YouTube Shorts",
    description: "Bottom bar, strong contrast, caption-safe margin.",
    bar: {
      ...base,
      position: "bottom",
      marginY: 220,
      thickness: 10,
      radius: 6,
      fillColor: "#ff3b3b",
      trackColor: "#ffffff",
      trackOpacity: 0.3,
      widthPercent: 88,
    },
  },
  {
    id: "tiktok-clean",
    name: "TikTok Clean",
    description: "High visibility, vertical-aware, sleek.",
    bar: {
      ...base,
      position: "bottom",
      marginY: 180,
      thickness: 6,
      radius: 6,
      fillColor: "#ffffff",
      trackColor: "#000000",
      trackOpacity: 0.35,
      shadowEnabled: true,
      widthPercent: 90,
    },
  },
  {
    id: "podcast-clip",
    name: "Podcast Clip",
    description: "Lower, thicker, good for face cam + captions.",
    bar: {
      ...base,
      position: "bottom",
      marginY: 120,
      thickness: 14,
      radius: 8,
      fillColor: "#fbbf24",
      trackColor: "#ffffff",
      trackOpacity: 0.2,
      widthPercent: 86,
    },
  },
  {
    id: "gaming-neon",
    name: "Gaming Neon",
    description: "Glow, gradient, streamer-style.",
    bar: {
      ...base,
      position: "bottom",
      thickness: 12,
      radius: 8,
      glowEnabled: true,
      glowColor: "#22d3ee",
      gradientEnabled: true,
      gradientFrom: "#22d3ee",
      gradientTo: "#a855f7",
      trackColor: "#1e1b4b",
      trackOpacity: 0.6,
      animation: "smooth",
    },
  },
  {
    id: "course-video",
    name: "Course Video",
    description: "Subtle, professional, non-distracting.",
    bar: {
      ...base,
      position: "top",
      marginY: 40,
      thickness: 3,
      radius: 1,
      fillColor: "#60a5fa",
      trackColor: "#ffffff",
      trackOpacity: 0.15,
    },
  },
  {
    id: "corporate-clean",
    name: "Corporate Clean",
    description: "Blue/white for LinkedIn and training.",
    bar: {
      ...base,
      position: "bottom",
      thickness: 6,
      radius: 0,
      fillColor: "#1d4ed8",
      trackColor: "#cbd5e1",
      trackOpacity: 0.5,
      widthPercent: 100,
      marginX: 0,
      marginY: 0,
    },
  },
  {
    id: "documentary-timeline",
    name: "Documentary Timeline",
    description: "Muted, subtle track and progress.",
    bar: {
      ...base,
      position: "bottom",
      thickness: 5,
      radius: 0,
      fillColor: "#e7e5e4",
      trackColor: "#78716c",
      trackOpacity: 0.4,
      widthPercent: 80,
      marginY: 80,
    },
  },
];

export const DEFAULT_PRESET_ID = "minimal-creator";

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
